--- 
text_extensions: [ 'css', 'erb', 'haml', 'htm', 'html', 'js', 'less', 'markdown', 'md', 'php', 'rb', 'sass', 'txt', 'scss' ]
output_dir: output
data_sources: 
- items_root: /
  layouts_root: /
  type: filesystem_unified
